### ISSUE TITLE
This project has no license

### ISSUE THREAD

**Issue by fieldju** [tepez/auth0-rules-types#5]
Could you add a license to this project such as the [Apache v2](https://www.apache.org/licenses/LICENSE-2.0)

**edit**:

I see this: https://github.com/tepez/auth0-rules-types/blob/6fe21dc54d23aa701e0565af2865a67425df8cd5/package.json#L15
If this project is licensed under the MIT license could you add that in a license file?

https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by tomyam1** [comment]
Should be included in 0.3.1
